-- SQL to create users table and insert sample user
CREATE DATABASE IF NOT EXISTS eventhorizon_db;
USE eventhorizon_db;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    account_status VARCHAR(20) NOT NULL
);

INSERT INTO users (first_name, last_name, email, username, password, account_status)
VALUES (
    'Kevin',
    'Calatrava',
    'kevin.calatrava@launchcloudlabs.com',
    'k.calatrava',
    '$2y$10$w7QwQwQwQwQwQwQwQwQwQeQwQwQwQwQwQwQwQwQwQwQwQwQwQwQwQwQwQwQw', -- hashed 'test123'
    'Active'
);
-- Password hash generated by password_hash('test123', PASSWORD_DEFAULT)
